schema-version: v2
kind: plugin
metadata:
  name: nodejs-base-config
  display-name: nodejs-base-config
  description: Plugin to create a base config of a nodejs app
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - nodejs
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: False
  repository: git@github.com:maxleycostazup/stackspot-base-nodejs-app.git
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Api
  stk-projects-only: false
  inputs:
    - label: App name
      name: APPLICATION_NAME
      type: text
      required: true
      default: nodejs-application
      pattern: '^[a-z]+(?:-[a-z]+)*$'
      help: 'Inform your application name (e.g.: nodejs-application)'
    - label: App description
      name: APPLICATION_DESCRIPTION
      type: text
      required: false
      help: 'Inform the goal of your application'
